-- MySQL Script generated by MySQL Workbench
-- Mon May 18 20:27:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Notebooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notebooks` (
  `UUID` INT NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(45) NULL,
  `Time_stamp` TIMESTAMP NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sections` (
  `UUID` INT NOT NULL AUTO_INCREMENT,
  `notebook` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `time_stamp` TIMESTAMP NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pages` (
  `UUID` INT NOT NULL AUTO_INCREMENT,
  `section` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `content` JSON NULL,
  `time_stamp` TIMESTAMP NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
